backend: tensorflow
class_name: Functional
config:
  input_layers:
  - - block
    - 0
    - 0
  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple
      - null
      - 8
      - 8
      dtype: float32
      name: block
      ragged: false
      sparse: false
    inbound_nodes: []
    name: block
  - class_name: Reshape
    config:
      dtype: float32
      name: reshape
      target_shape: !!python/tuple
      - 64
      trainable: true
    inbound_nodes:
    - - - block
        - 0
        - 0
        - {}
    name: reshape
  - class_name: Custom>SortLayer
    config:
      dtype: float32
      name: sort
      trainable: true
    inbound_nodes:
    - - - reshape
        - 0
        - 0
        - {}
    name: sort
  - class_name: Reshape
    config:
      dtype: float32
      name: reshape_1
      target_shape: !!python/tuple
      - 1
      - 64
      trainable: true
    inbound_nodes:
    - - - sort
        - 0
        - 0
        - {}
    name: reshape_1
  - class_name: Bidirectional
    config:
      dtype: float32
      layer:
        class_name: LSTM
        config:
          activation: tanh
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dropout: 0.0
          dtype: float32
          go_backwards: false
          implementation: 2
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: lstm
          recurrent_activation: sigmoid
          recurrent_constraint: null
          recurrent_dropout: 0.0
          recurrent_initializer:
            class_name: Orthogonal
            config:
              gain: 1.0
              seed: null
          recurrent_regularizer: null
          return_sequences: false
          return_state: false
          stateful: false
          time_major: false
          trainable: true
          unit_forget_bias: true
          units: 256
          unroll: false
          use_bias: true
      merge_mode: concat
      name: bidirectional
      trainable: true
    inbound_nodes:
    - - - reshape_1
        - 0
        - 0
        - {}
    name: bidirectional
  - class_name: BatchNormalization
    config:
      axis: !!python/object/apply:tensorflow.python.training.tracking.data_structures.ListWrapper
      - - 1
      beta_constraint: null
      beta_initializer:
        class_name: Zeros
        config: {}
      beta_regularizer: null
      center: true
      dtype: float32
      epsilon: 0.001
      gamma_constraint: null
      gamma_initializer:
        class_name: Ones
        config: {}
      gamma_regularizer: null
      momentum: 0.99
      moving_mean_initializer:
        class_name: Zeros
        config: {}
      moving_variance_initializer:
        class_name: Ones
        config: {}
      name: batch_normalization
      scale: true
      trainable: true
    inbound_nodes:
    - - - bidirectional
        - 0
        - 0
        - {}
    name: batch_normalization
  - class_name: Sequential
    config:
      layers:
      - class_name: InputLayer
        config:
          batch_input_shape: !!python/tuple
          - null
          - 512
          dtype: float32
          name: dense_input
          ragged: false
          sparse: false
      - class_name: Dense
        config:
          activation: linear
          activity_regularizer: null
          bias_constraint: null
          bias_initializer:
            class_name: Zeros
            config: {}
          bias_regularizer: null
          dtype: float32
          kernel_constraint: null
          kernel_initializer:
            class_name: GlorotUniform
            config:
              seed: null
          kernel_regularizer: null
          name: dense
          trainable: true
          units: 256
          use_bias: true
      - class_name: BatchNormalization
        config:
          axis: !!python/object/apply:tensorflow.python.training.tracking.data_structures.ListWrapper
          - - 1
          beta_constraint: null
          beta_initializer:
            class_name: Zeros
            config: {}
          beta_regularizer: null
          center: true
          dtype: float32
          epsilon: 0.001
          gamma_constraint: null
          gamma_initializer:
            class_name: Ones
            config: {}
          gamma_regularizer: null
          momentum: 0.99
          moving_mean_initializer:
            class_name: Zeros
            config: {}
          moving_variance_initializer:
            class_name: Ones
            config: {}
          name: batch_normalization_1
          scale: true
          trainable: true
      - class_name: Activation
        config:
          activation: linear
          dtype: float32
          name: activation
          trainable: true
      name: sequential
    inbound_nodes:
    - - - batch_normalization
        - 0
        - 0
        - {}
    name: sequential
  - class_name: Custom>QuasiEntropyLayer
    config:
      dtype: float32
      name: quasi_entropy
      trainable: true
    inbound_nodes:
    - - - sequential
        - 1
        - 0
        - {}
    name: quasi_entropy
  name: block_entropy_estimator
  output_layers:
  - - quasi_entropy
    - 0
    - 0
keras_version: 2.4.0
